### PR TITLE
fix: account for afters of non-root nodes

### LINKED ISSUE #18: The fix flag breaks the indentation
If I run Stylelint with the `--fix` flag, it moves the indentation:

Screenshot 2021-12-09 at 00 33 55

Example with: https://github.com/IBM/pwa-lit-template/compare/stylelint-14

- To run Stylelint `npm run lint:stylelint`
- To run Stylelint with auto fix `npm run lint:stylelint -- --fix`

### PR DESCRIPTION
**Pull request by 43081j**
Fixes #18 

cc @abdonrd

I've published `postcss-lit@next` if you want to try it

### CODE REVIEW

**Comment by abdonrd** [comment]
I just tried it! It seems to solve the problem from before, but a new one arises.

Screenshot 2021-12-11 at 13 50 06

See the multiline `main`.

**Comment by abdonrd** [comment]
Thanks @43081j! Now it works well in the `IBM/pwa-lit-template`! 👏🏻 

But trying in another project I see more changes:
Screenshot 2021-12-13 at 12 11 41

Screenshot 2021-12-13 at 12 14 00

Also leaving an entire file empty:
Screenshot 2021-12-13 at 12 12 51

**Comment by 43081j** [comment]
😞  its the same problem in a different place.

i think i need to solve it globally somehow.

basically, various AST nodes have string values in them (e.g. `rule.selector`, `decl.value`, etc). they contain the surrounding whitespace, rather than using the before/after strings we correct.

in this case, the declaration's value needs correcting just the same way we corrected the rule's selector.

the empty file thing is another issue but im sure that'll be an easy fix.

thanks so much for testing, ill see if i can sort them tonight

**Comment by 43081j** [comment]
just an update...

by some miracle i think i may have fixed it for all node types. tomorrow i'll add more tests to confirm this then publish a new `@next` build for you to try @abdonrd 

there's a lot of places indentation can exist so i just need to make sure we have tests for enough of them

**Comment by abdonrd** [comment]
Thanks @43081j!

Now just this auto fix:

Screenshot 2021-12-14 at 01 05 00

But I don't know if it is a `postcss-lit` thing or is because Stylelint v14.

**Comment by abdonrd** [comment]
Well, and still happens that component files are empty.

Screenshot 2021-12-13 at 12 12 51

**Comment by 43081j** [comment]
@abdonrd the first one is stylelint 14.x, they introduced a new recommended rule which migrates all rgb values to space-separated. `rgba(r, g, b, a)` becomes `rgb(r g b / a)`

we had the same huge change in our repos :D was a surprise to me too

i'll try fix the empty file thing tonight

**Comment by 43081j** [comment]
@abdonrd i've fixed the empty file problem now. published a new `@next`

**Comment by abdonrd** [comment]
Yay! It works now, thanks @43081j ! 👏

**Comment by 43081j** [comment]
awesome, ill get it published soon as i can.

thanks so much for testing

**Pull request merged**
